import { useNavigate } from "react-router";
import { Button } from "@/components/ui/button";
import { Star, ArrowLeft, Lock } from "lucide-react";

function GlassPanel({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return (
    <div className={`rounded-2xl border border-white/10 bg-[#18181B]/70 backdrop-blur-xl shadow-[0_8px_32px_rgba(0,0,0,0.3)] ${className}`}>
      {children}
    </div>
  );
}

export default function Privacy() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen">
      <div className="fixed inset-0 -z-10">
        <div className="absolute inset-0 bg-[#0D0D0D]" />
        <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-[#16A34A]/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3" />
      </div>

      <nav className="relative z-20 px-4 sm:px-6 py-5 border-b border-white/5">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2.5 cursor-pointer" onClick={() => navigate("/")}>
            <div className="w-8 h-8 rounded-lg bg-[#16A34A] flex items-center justify-center shadow-lg shadow-[#16A34A]/25">
              <Star className="w-4 h-4 text-white fill-white" />
            </div>
            <span className="font-bold text-sm text-white tracking-wide">STAR CATCH</span>
          </div>
          <Button variant="outline" size="sm" onClick={() => navigate(-1)} className="border-white/10 bg-white/5 hover:bg-white/10 text-[#A1A1AA] cursor-pointer text-xs">
            <ArrowLeft className="w-3.5 h-3.5 mr-1.5" /> Back
          </Button>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-10">
        <div className="flex items-center gap-3 mb-8">
          <div className="w-10 h-10 rounded-xl bg-[#16A34A]/15 flex items-center justify-center">
            <Lock className="w-5 h-5 text-[#16A34A]" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white">Privacy Policy</h1>
            <p className="text-xs text-[#A1A1AA]">Last updated: August 24, 2026</p>
          </div>
        </div>

        <GlassPanel className="p-6 sm:p-8 space-y-8">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Introduction</h2>
            <p className="text-sm text-[#A1A1AA] leading-relaxed">
              STAR CATCH Reviews and Feedback Agency Bd ("STAR CATCH", "we", "us", or "our") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our Platform. This policy is formulated in compliance with the Bangladesh Information and Communication Technology (ICT) Act 2006 (as amended in 2013), the Digital Security Act 2018, and other applicable data protection laws of Bangladesh. By using STAR CATCH, you agree to the collection and use of information in accordance with this policy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Information We Collect</h2>
            <p className="text-sm text-[#A1A1AA] leading-relaxed mb-3">We may collect the following types of information:</p>
            <ul className="list-disc list-inside text-sm text-[#A1A1AA] leading-relaxed space-y-1.5 ml-4">
              <li><strong className="text-white">Account Information:</strong> Name, email address, and authentication credentials (for account creation and login).</li>
              <li><strong className="text-white">Business Information:</strong> Business name, category, logo URL, Google Review URL, and custom URL slug.</li>
              <li><strong className="text-white">Customer Feedback Data:</strong> Names, phone numbers, email addresses, and written feedback submitted by end customers through your review gatekeeper.</li>
              <li><strong className="text-white">Usage Data:</strong> Interaction timestamps, star ratings, redirect events, and analytics data generated by your customers' use of the review gatekeeper.</li>
              <li><strong className="text-white">Payment Information:</strong> Transaction IDs, sender phone numbers, and payment gateway details submitted for subscription verification.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. How We Use Your Information</h2>
            <p className="text-sm text-[#A1A1AA] leading-relaxed mb-3">We use the collected information to:</p>
            <ul className="list-disc list-inside text-sm text-[#A1A1AA] leading-relaxed space-y-1.5 ml-4">
              <li>Provide, maintain, and improve the Platform and its features</li>
              <li>Process subscription payments and manage your account</li>
              <li>Send analytics and performance reports to your dashboard</li>
              <li>Route customer feedback to the appropriate business owner</li>
              <li>Communicate with you about your account, updates, and support requests</li>
              <li>Detect and prevent fraud, abuse, or unauthorized access</li>
              <li>Comply with legal obligations under the ICT Act 2006 and Digital Security Act 2018</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Data Protection &amp; ICT Act Compliance</h2>
            <p className="text-sm text-[#A1A1AA] leading-relaxed mb-3">
              STAR CATCH handles your data in compliance with the Bangladesh Information and Communication Technology (ICT) Act 2006 (as amended in 2013) and the Digital Security Act 2018. Specifically:
            </p>
            <ul className="list-disc list-inside text-sm text-[#A1A1AA] leading-relaxed space-y-1.5 ml-4">
              <li><strong className="text-white">No Sale of Personal Data:</strong> Private feedback data submitted by end-users (1-3 star ratings) is strictly processed solely to inform the respective business owner. This data will never be sold, traded, or shared with third-party data brokers, marketing agencies, or any entity unrelated to the service.</li>
              <li><strong className="text-white">Lawful Processing:</strong> We collect and process data only for the specific purposes outlined in this policy and only with a lawful basis (consent, contractual necessity, or legitimate interest).</li>
              <li><strong className="text-white">Data Minimization:</strong> We collect only the minimum amount of data necessary to provide the Platform's features and do not engage in excessive data collection.</li>
              <li><strong className="text-white">Security Measures:</strong> We implement technical and organizational measures to protect personal data against unauthorized access, alteration, disclosure, or destruction, in accordance with the security standards required by the ICT Act.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Data Sharing</h2>
            <p className="text-sm text-[#A1A1AA] leading-relaxed">
              We do not sell, trade, or rent your personal information to third parties. Customer feedback data (names, phone numbers, messages) submitted through your review gatekeeper is shared only with the business owner who configured that gatekeeper. We may share information with third-party service providers who assist in operating the Platform (e.g., Convex for database hosting, Google for authentication), subject to confidentiality obligations and only to the extent necessary to provide the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Data Security</h2>
            <p className="text-sm text-[#A1A1AA] leading-relaxed">
              We implement industry-standard security measures to protect your data, including encryption in transit (TLS/HTTPS), secure authentication via Convex Auth, and role-based access controls. We take reasonable steps to protect personal data from unauthorized access, in compliance with the security requirements set forth in the Digital Security Act 2018. However, no method of electronic transmission or storage is 100% secure, and we cannot guarantee absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Data Retention</h2>
            <p className="text-sm text-[#A1A1AA] leading-relaxed">
              We retain your data for as long as your account is active or as needed to provide the Platform. Customer feedback data is retained in your account until you delete it or your account is terminated. Analytics data is retained for the duration of your subscription and may be aggregated after account termination. We do not retain personal data longer than is necessary for the purposes for which it was collected.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Your Rights</h2>
            <p className="text-sm text-[#A1A1AA] leading-relaxed mb-3">You have the right to:</p>
            <ul className="list-disc list-inside text-sm text-[#A1A1AA] leading-relaxed space-y-1.5 ml-4">
              <li>Access and review the personal data we hold about you</li>
              <li>Request correction of inaccurate or incomplete data</li>
              <li>Request deletion of your personal data (subject to legal obligations)</li>
              <li>Export your data in a portable format</li>
              <li>Withdraw consent for data processing where applicable</li>
            </ul>
            <p className="text-sm text-[#A1A1AA] leading-relaxed mt-3">
              To exercise any of these rights, contact us via email at starcatchbd@gmail.com or through our platform support channels.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Cookies &amp; Tracking</h2>
            <p className="text-sm text-[#A1A1AA] leading-relaxed">
              The Platform uses essential cookies and local storage for authentication and session management. We do not use third-party advertising cookies or tracking pixels. Your browsing data is not shared with advertisers.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">10. Changes to This Policy</h2>
            <p className="text-sm text-[#A1A1AA] leading-relaxed">
              We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated "Last updated" date. Your continued use of the Platform after changes are posted constitutes acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">11. Governing Law &amp; Jurisdiction</h2>
            <p className="text-sm text-[#A1A1AA] leading-relaxed">
              This Privacy Policy is governed by the laws of Bangladesh, including the Bangladesh Information and Communication Technology (ICT) Act 2006 (as amended in 2013) and the Digital Security Act 2018. All legal disputes arising out of or in connection with this policy are strictly subject to the exclusive jurisdiction of the courts of Dhaka, Bangladesh.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">12. Contact Us</h2>
            <p className="text-sm text-[#A1A1AA] leading-relaxed">
              If you have questions about this Privacy Policy or wish to exercise your data rights, please contact us via WhatsApp at +880 1673-903919, email us at starcatchbd@gmail.com, or reach us through our platform support channels.
            </p>
          </section>
        </GlassPanel>

        <div className="text-center mt-8 mb-12">
          <Button onClick={() => navigate("/")} className="bg-[#16A34A] hover:bg-[#16A34A]/90 text-white font-semibold cursor-pointer">
            <Star className="w-4 h-4 mr-2 fill-white" /> Back to Home
          </Button>
        </div>
      </div>
    </div>
  );
}
